added jenkins installation inside cluster

diff --git a/app/jenkinsfile b/app/jenkinsfile
--- a/app/jenkinsfile
+++ b/app/jenkinsfile
@@ -17,20 +17,21 @@ pipeline {
             }
         }
 
-        stage('Build & Push Docker Image') {
+        stage('Build Docker Image') {
             steps {
                 script {
                     echo "Building Docker image: $DOCKER_IMAGE:$IMAGE_TAG"
                     def image = docker.build("$DOCKER_IMAGE:$IMAGE_TAG")
+                }
+            }
+        }
 
-                    echo "Pushing Docker image to Docker Hub..."
-                    docker.withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', 
-                                  usernameVariable: 'USERNAME', 
-                                  passwordVariable: 'PASSWORD')]) {
-    sh "echo $PASSWORD | docker login -u $USERNAME --password-stdin"
-    sh "docker push noa10203040/flask_app:$IMAGE_TAG"
-}
-
+        stage('Push Docker Image to Docker Hub') {
+            steps {
+                script {
+                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
+                        echo "Pushing Docker image: $DOCKER_IMAGE:$IMAGE_TAG"
+                        docker.image("$DOCKER_IMAGE:$IMAGE_TAG").push()
                     }
                 }
             }
@@ -39,13 +40,10 @@ pipeline {
         stage('Deploy to EKS via Helm') {
             steps {
                 script {
-                    echo "Deploying to EKS namespace: $K8S_NAMESPACE"
+                    echo "Deploying Helm chart to namespace: $K8S_NAMESPACE"
+                    sh "kubectl create namespace $K8S_NAMESPACE || true"
                     sh """
-                        # מוסיפים ריפו רק אם צריך
-                        helm repo add mycharts https://example.com/helm-charts || true
                         helm repo update
-
-                        # מפרסים או מעלים את ה-Helm release
                         helm upgrade --install $HELM_RELEASE $HELM_CHART_PATH \
                             --namespace $K8S_NAMESPACE \
                             --set flask.image=$DOCKER_IMAGE \
@@ -59,10 +57,10 @@ pipeline {
 
     post {
         success {
-            echo "✅ Deployment successful! Image: $DOCKER_IMAGE:$IMAGE_TAG"
+            echo "Deployment successful! Image: $DOCKER_IMAGE:$IMAGE_TAG"
         }
         failure {
-            echo "❌ Deployment failed!"
+            echo "Deployment failed!"
         }
     }
 }
